# .pre-commit-config.yaml
default_stages: [commit]
repos:
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.83.2
      hooks:
          - id: terraform_fmt
          - id: terraform_validate
          - id: terraform_tflint
          - id: terraform_tfsec
          - id: checkov
    - repo: local
      hooks:
        - id: terraform-docs
          name: terraform-docs
          language: docker_image
          entry: quay.io/terraform-docs/terraform-docs:latest  # or, change latest to pin to a specific version
          args: ["markdown", "table", "--output-file", "README.md", "--output-mode", "inject", "./"]          # e.g. ["--output-file", "README.md", "./mymodule/path"]
          pass_filenames: false
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            args: [--unsafe]
          - id: check-added-large-files
